### ISSUE TITLE
support for react 17

### ISSUE THREAD

**Issue by dioscuroi** [plangrid/react-file-viewer#180]
Installation fails with react 17 due to dependency error. It will be highly appreciated if the library supports the latest versions of react as well. Thanks!!

**Comment by muftisamiullah** [comment]
does it work or not because im a getting an error while installing 

code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: acade-learn@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.6.3" from react-file-viewer@1.2.1
npm ERR! node_modules/react-file-viewer
npm ERR!   react-file-viewer@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by arslan990** [comment]
Any update on this?

**Comment by muftisamiullah** [comment]
Downgrade ur react version

**Comment by passedByMe** [comment]
@muftisamiullah mustafa bozi txa

**Comment by nomoney4me** [comment]
> Downgrade ur react version
If this is the official answer then I think the README.md should reflect that. At the moment, it says: `Note this module works best with react 16+` which implies that anything above version 16 (ie. 17) should work as well.

**Comment by mdsaddamvol** [comment]
any solution other then downgrade react

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: halo_admin@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.6.3" from react-file-viewer@1.2.1
npm ERR! node_modules/react-file-viewer
npm ERR!   react-file-viewer@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

**Comment by arslan990** [comment]
Run command npm i --legacy-peer-deps, this works for me.
